### PR TITLE
Helping out a picky C++ compiler with initializing an array.

### LINKED ISSUE #269: Use of deleted RationalConstant default constructor in Units constructor
Hit this compile error on a newly-updated Linux box with an extra persnickety C++ compiler:

```
/home/jeff/projects/sandia/scream/components/scream/src/share/util/units.hpp:55:31: error: use of deleted function ‘scream::util::RationalConstant::RationalConstant()’
   55 |    , m_exp_format (Format::Rat)
      |                               ^
In file included from /home/jeff/projects/sandia/scream/components/scream/src/share/util/units.hpp:4,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/field/field_identifier.hpp:6,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/field/field_header.hpp:4,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/field/field.hpp:4,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/util/scream_test_utils.hpp:6,
                 from /home/jeff/projects/sandia/scream/components/scream/src/share/util/scream_catch_main.cpp:7:
/home/jeff/projects/sandia/scream/components/scream/src/share/util/rational_constant.hpp:48:3: note: declared here
   48 |   RationalConstant () = delete;
```

Looks like we need to be more specific about how to initialize the `m_exp_format` field in the Unit class for that constructor. Anyone have any thoughts? I'm not familiar enough with how this stuff is used to have an opinion yet.

### PR DESCRIPTION
**Pull request by jeff-cohere**
A C++ compiler I'm using (looks like GNU 9.2.1) has decided to be picky. I think what's going on is it's having trouble distinguishing an array initialization (of zeros) from default initialization for that array.

Fixes #269

### CODE REVIEW

File: components/scream/src/share/util/units.hpp [hunk 1]
```diff
@@ -51,7 +51,9 @@ class Units {
   // Construct a non-dimensional quantity
   Units (const ScalingFactor& scaling)
    : m_scaling {scaling}
-   , m_units{0,0,0,0,0,0,0}
+   , m_units{RationalConstant(0), RationalConstant(0), RationalConstant(0),
```
Comment (jgfouca) [inline components/scream/src/share/util/units.hpp]: Did you try this:

```
, m_units{ {0}, {0}, ... }
```

Comment (bartgol) [reply components/scream/src/share/util/units.hpp]: I think Jim's solution may work.

**Comment by bartgol** [comment]
@jeff-cohere While you're at it, I'm looking at the code in vim, and the bg clang compiler is telling me that the defaulted assignment op of Units, ScalingFactor, and RationalConstant are implicitly deleted. I'm assuming it's because RationalConstant has some const members, so it can't be re-assigned after contruction. Would you mind removing those assignment ops?

**Comment by jeff-cohere** [comment]
Sure. I'll make these changes and resubmit.

File: components/scream/src/share/util/units.hpp (hunk 1 above)
Comment (jeff-cohere) [reply components/scream/src/share/util/units.hpp]: Just tried that. Same error. This is probably one of those things they put in before it was fully baked. :-/

**Comment by jeff-cohere** [comment]
Looks like the testing failed because of the "out of space on device" error. Anything else needed to push this along (provided we fix that problem)?

**Comment by ambrad** [comment]
I'm OK with merging based on bowman and white. I'll do that.
