### PR TITLE
Fix dimensions of dry/wet mixing variables in p3

### LINKED ISSUE #1393: Dimension 1 of array 'drymmr' has extent 3 instead of 4 with SMS_D_P64x2.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_gnu
Using GNU and DEBUG, I see following error with `SMS_D_P64x2.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_gnu`

```
 8: At line 60 of file /global/cscratch1/sd/ndk/wacmy/s46-feb1/components/eam/src/physics/cam/physics_utils.F90
 8: Fortran runtime error: Dimension 1 of array 'drymmr' has extent 3 instead of 4
 8: 
```

It was suggested to try 

`qv_dry(1:ncol,:)      = calculate_drymmr_from_wetmmr(ncol, pver, qv_wet_in,              qv_wet_in)`

in `components/eam/src/physics/cam/micro_p3_interface.F90`

I still see same error with this change, but there may be other lines that need this change

Originally thought this issue was related to https://github.com/E3SM-Project/scream/issues/1317, but now think it's separate.

Using Intel and DEBUG, a different message that I show here https://github.com/E3SM-Project/scream/issues/1394

### PR DESCRIPTION
**Pull request by singhbalwinder**
The dimensions of dry/wet conversion variables are set to (:ncol,:pver) to possibly fix issue #1393
.
BFB
Fixes #1393

### CODE REVIEW

**Review by ambrad — APPROVED** [review]

File: components/eam/src/physics/cam/micro_p3_interface.F90 [hunk 1]
```diff
@@ -1005,16 +1005,16 @@ subroutine micro_p3_tend(state, ptend, dtime, pbuf)
...
-    qv_prev_dry = calculate_drymmr_from_wetmmr(ncol, pver, qv_prev_wet,            qv_wet_in)
-    cldliq      = calculate_drymmr_from_wetmmr(ncol, pver, state%q(:,:,ixcldliq),  qv_wet_in)
-    numliq      = calculate_drymmr_from_wetmmr(ncol, pver, state%q(:,:,ixnumliq),  qv_wet_in)
-    rain        = calculate_drymmr_from_wetmmr(ncol, pver, state%q(:,:,ixrain),    qv_wet_in)
-    numrain     = calculate_drymmr_from_wetmmr(ncol, pver, state%q(:,:,ixnumrain), qv_wet_in)
-    ice         = calculate_drymmr_from_wetmmr(ncol, pver, state%q(:,:,ixcldice),  qv_wet_in)
-    qm          = calculate_drymmr_from_wetmmr(ncol, pver, state%q(:,:,ixcldrim),  qv_wet_in) !Aaron, changed ixqm to ixcldrim to match Kai's code
-    numice      = calculate_drymmr_from_wetmmr(ncol, pver, state%q(:,:,ixnumice),  qv_wet_in)
-    rimvol      = calculate_drymmr_from_wetmmr(ncol, pver, state%q(:,:,ixrimvol),  qv_wet_in)
+    qv_dry(:ncols,:pver)      = calculate_drymmr_from_wetmmr(ncol, pver, qv_wet_in,              qv_wet_in)
```
Comment (ambrad) [inline components/eam/src/physics/cam/micro_p3_interface.F90:1008]: What's the difference between `ncols` and `ncol`?

Comment (singhbalwinder) [reply components/eam/src/physics/cam/micro_p3_interface.F90:1008]: That is a typo. it should be `ncol`. I fixed it in my local branch before running the test but forgot to push it to GitHub. Thanks for catching that.

**Review by ndkeen — APPROVED** [review]

**Comment by ndkeen** [comment]
This change also fixes the error with Intel DEBUG (which showed up very differently).

Fixes https://github.com/E3SM-Project/scream/issues/1394

**Comment by AaronDonahue** [comment]
This PR might need to be rebased and rerun to pass the AT.  I'll do that.  Setting the RETEST label.

**Comment by AaronDonahue** [comment]
@ambrad or @ndkeen , one of you will need to reapprove since I rebased.

**Review by ambrad — APPROVED** [review]
