### PR TITLE
Make the handling of the diagnostic timestamp more robust.

### LINKED ISSUE #1810: Output field not initialized error when adding LiqWaterPath output and related fields
The ability to add vertically integrated cloud liquid, vapor, ice, and rain water paths was added with PR#1761. With master `35de2d4`, when `LiqWaterPath` is requested as an output, the following error results in a crash. Although note tested, I suspect it also affects `VapWaterPath`, `IceWaterPath`, and `RainWaterPath`.
```
5376: terminate called after throwing an instance of 'std::logic_error'
5376:   what():  /global/u1/t/terai/SCREAM/scream/master/components/scream/src/share/io/scorpio_output.cpp:193: FAIL:
5376: field.get_header().get_tracking().get_time_stamp().is_valid()
5376: Error! Output field 'LiqWaterPath' has not been initialized yet
5376: .
```

### PR DESCRIPTION
**Pull request by bartgol**
Before, we were setting the diag timestamp in `scorpio_output.cpp`, as soon as we created it, by grabbing the timestamp of one of the diagnostic required fields. However, we never checked that the timestamp was valid. In certain cases, additionally, all the required fields might have an invalid timestamp. This can happen if all the required fields are _computed_ in the ATM, so that none of them has a valid timestamp when the IO class is created at init time.

Fix #1810

### CODE REVIEW

File: components/scream/src/share/atm_process/atmosphere_diagnostic.hpp [hunk 1]
```diff
@@ -43,14 +43,16 @@ class AtmosphereDiagnostic : public AtmosphereProcess
...
-
   void set_computed_field (const Field& f) final;
   void set_computed_group (const FieldGroup& group) final;
+
+  void compute_diagnostic ();
 protected:
 
+  virtual void compute_diagnostic_impl () = 0;
+
+  void run_impl (const int /* dt */);
```
Comment (AaronDonahue) [inline components/scream/src/share/atm_process/atmosphere_diagnostic.hpp:54]: is it safe to say that we don't actually ever use `run_impl` now?

**Review by AaronDonahue — DISMISSED** [review]

File: components/scream/src/share/atm_process/atmosphere_diagnostic.hpp (hunk 1 above)
Comment (bartgol) [reply components/scream/src/share/atm_process/atmosphere_diagnostic.hpp:54]: Well, probably. But until we refactor the diag class, making it independent of AtmosphereProcess, we don't want to risk someone calling the run methods. Since it's easy to fwd a call to run to a call to compute_diagnostic, we might as well do it.

Long term, I think Diagnostic should not be an atm process.

Comment (AaronDonahue) [reply components/scream/src/share/atm_process/atmosphere_diagnostic.hpp:54]: I agree

**Review by AaronDonahue — APPROVED** [review]
