### PR TITLE
SHOC surface sensible heat flux fix

### LINKED ISSUE #1333: SHOC interface (cpp code) surface flux index bug
https://github.com/E3SM-Project/scream/blob/4b5842e40bc0108a765e405c932087279a542e58/components/scream/src/physics/shoc/atmosphere_macrophysics.hpp#L162-L165

When computing the surface fluxes in the SHOC cpp interface there appears to be a index bug when attempting to use the interface level density (rho_i) at the surface.  Instead of "rrho_i(i,nlev_v)[nlev_p]" this needs to be "rrho_i(i,nlevi_v)[nlevi_p]" for the lines referenced.  The current cpp implementation is at odds with the F90 implementation and using density at the wrong level.

Of course, with my ignorance of cpp code, there is the possibility I am misreading something?...

### PR DESCRIPTION
**Pull request by bogensch**
Takes into account exner function when passing surface sensible heat flux to SHOC.  PR is answer changing.  However, all tests pass because the SHOC interface is NOT exercised in the SHOC run and compare tests.

Also this PR closes #1333

### CODE REVIEW

**Comment by bogensch** [comment]
@AaronDonahue and @tcclevenger if you could focus on the cpp changes (since I am super uncomfortable with the cpp code) to make sure I did them correctly and consistently, it would be greatly appreciated.

File: components/scream/src/physics/shoc/atmosphere_macrophysics.hpp [hunk 1]
```diff
@@ -159,7 +159,11 @@ class SHOCMacrophysics : public scream::AtmosphereProcess
 
       const int nlev_v = (nlev-1)/Spack::n;
       const int nlev_p = (nlev-1)%Spack::n;
+      const auto& exner_int = PF::exner_function(p_int(i,nlevi_v)[nlevi_p]);
+      const auto& inv_exner_int_surf = 1/exner_int;
+
       wpthlp_sfc(i) = surf_sens_flux(i)/(cpair*rrho_i(i,nlev_v)[nlev_p]);
```
Comment (tcclevenger) [inline components/scream/src/physics/shoc/atmosphere_macrophysics.hpp:165]: Should all the below `*_sfc(i) =` lines be changed to use `(nlevi_v)[nlevi_p]`?
```suggestion
      wpthlp_sfc(i) = surf_sens_flux(i)/(cpair*rrho_i(i,nlevi_v)[nlevi_p]);
```

File: components/scream/src/physics/shoc/atmosphere_macrophysics.cpp [hunk 2]
```diff
@@ -287,7 +288,7 @@ void SHOCMacrophysics::initialize_impl ()
   const Real z_surf = 0.0;
 
   shoc_preprocess.set_variables(m_num_cols,m_num_levs,m_num_tracers,z_surf,m_cell_area,
-                                T_mid,p_mid,pseudo_density,omega,phis,surf_sens_flux,surf_latent_flux,
+                                T_mid,p_mid,p_int,pseudo_density,omega,phis,surf_sens_flux,surf_latent_flux,
                                 surf_mom_flux,qv,qc,tke,tke_copy,z_mid,z_int,cell_length,
                                 dse,rrho,rrho_i,thv,dz,zt_grid,zi_grid,wpthlp_sfc,wprtp_sfc,upwp_sfc,vpwp_sfc,
                                 wtracer_sfc,wm_zt,inv_exner,thlm,qw);
```
Comment (tcclevenger) [inline components/scream/src/physics/shoc/atmosphere_macrophysics.cpp:294]: A few lines down there is 
```
input.presi  = get_field_in("p_int").get_view<const Spack**>();
```

Could you change this to 
```
input.presi  = p_int;
```
since we are now declaring `p_int`?

**Review by tcclevenger — COMMENTED** [review]
Just a comment about using `nlevi` indexing. And a cosmetic request inside `SHOCMacrophysics::initialize_impl ()`. Otherwise the c++ looks good to me.

**Review by tcclevenger — APPROVED** [review]
