### PR TITLE
Call MPI_Abort in CIME runs when an exception is thrown inside EAMxx

### LINKED ISSUE #2964: Call MPI_Abort on exceptions.
Two approaches:

1. Add MPI_Abort to the exception macros.
2. In the-top level C++ routine, wrap everything in a try-catch block with a catch-all block: `catch (...) { /* print mesage */;  MPI_Abort(comm, -1); }`.

### PR DESCRIPTION
**Pull request by bartgol**
This ensures that the whole job is terminated. The MPI standard does not guarantee that an uncaught exception will cause the whole MPI job to terminate.

Note: this *may* fix the very long hangs we were sometimes getting when the code crashed, and yet the job did not terminate.

Fixes #2964

### CODE REVIEW

File: components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp [hunk 1]
```diff
@@ -57,10 +57,15 @@ void fpe_guard_wrapper (const Lambda& f) {
   try {
     f();
   } catch (std::exception &e) {
```
Comment (ambrad) [inline components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp:59]: Any reason not to change this to `catch (...)` for greater generality?

Comment (bartgol) [reply components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp:59]: Yeah, we can do that

Comment (bartgol) [reply components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp:59]: Ah, but I want to print the exception message.

Comment (bartgol) [reply components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp:59]: I'll do a rethrow, then add `catch(...)` underneath

Comment (ambrad) [reply components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp:59]: Does that work? Or do you need to nest try blocks?

Comment (ambrad) [reply components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp:59]: I think you need to nest try-catch like this:

```c++
  try {
    try {
      throw std::exception();
    } catch (const std::exception& e) {
      printf("hi\n");
      throw;
    }
  } catch (...) {
    printf("hello\n");
  }
```

Comment (ambrad) [reply components/eamxx/src/mct_coupling/scream_cxx_f90_interface.cpp:59]: I'm fine with this, but you might consider nesting try-catch blocks to avoid redundant code:
```c++
  try {
    try {
      throw std::exception();
    } catch (const std::exception& e) {
      printf("hi\n");
      throw;
    }
  } catch (...) {
    printf("hello\n");
  }
```

**Review by ambrad — APPROVED** [review]

**Comment by bartgol** [comment]
The AT is failing b/c of FS issues on mappy. I'm not going to add RETEST, since the issue will likely linger for a while. We can retest/merge next week, it's not urgent.

**Comment by AaronDonahue** [comment]
@bartgol , is this just waiting for the AT to get back up to full functionality?  Could we manually test and then manually merge so that the PR doesn't linger?
